[project]
name = "kayanos"
authors = [
    { name = "Kayan", email = "hello@kayan.com"}
]
description = "Business orchestration layer for real-estate developers."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "frappe~=16.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
